#!/usr/bin/env python3

import sys
import os

import mvs_ftp


def update_project(project, libs=None, levels=None):
    prj_hlq, prj_release = project[:3], project[3:]
    all_data_sets = ftp.list_by_hlq('{}.*{}.ASM'.format(prj_hlq, prj_release))
    all_levels = set([ds.dsn[4:7] for ds in all_data_sets if ds.dsn.endswith('.ASM') and ds.is_pds()])
    all_libs = (
            ('ASM', 'zs'),
            ('MACLIB', 'zm'),
            ('C', 'c'),
            ('H', 'h'),
            ('CLIST', 'rexx'),
            ('ISPPLIB', 'isp'),
            ('PARMLIB', 'txt')
           )

    data_sets = (
                  (level, lib, suffix)
                    for lib, suffix in all_libs
                        if (not libs or (lib in libs))
                    for level in all_levels
                        if (not levels or (level in levels))
                )

    for level, lib, suffix in data_sets:
        dsn = '{}.{}{}.{}'.format(prj_hlq, level, prj_release, lib)
        ftp.pull_pds(dsn, os.path.join(project, dsn), suffix=suffix)


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Usage:")
        print("  update_project PRJNAME LIBS LEVELS")
        print("For exmaple:")
        print("  update_project ARH0205 ASM,MACLIB PRD,MNT")
        sys.exit()

    all_projects = (
        'ARH0205',
        'ARH0206',
        'AKD0205',
        'AKD0206',
        'MXH1002',
        'MXH1003',
        'MFA1003',
        'MFA1004'
        )

    project = sys.argv[1]
    if project not in all_projects:
        print("{} is not a available project".format(project))
        sys.exit()

    libs = []
    levels = []
    if len(sys.argv) > 2:
        libs = sys.argv[2].split(",")
    if len(sys.argv) > 3:
        levels = sys.argv[3].split(",")

    ftp = mvs_ftp.MvsFTP(host="dvlp", user="tspxm", passwd="Rocket2", logger=print)

    update_project(project=project, libs=libs, levels=levels)
